### PR TITLE
Create incremental.annotation.processors for Gradle

### LINKED ISSUE #61: Incremental compilation using Gradle is disabled
In my Gradle log, I noticed that it needs to perform a full recompilation for some of the subprojects because of `ClassIndexProcessor` usage.

```
> Task :compileJava
Created classpath snapshot for incremental compilation in 0.049 secs.
Class dependency analysis for incremental compilation took 0.257 secs.
Full recompilation is required because org.atteo.classindex.processor.ClassIndexProcessor is not incremental. Analysis took 0.359 secs.
```

The message looks odd to me because I thought the annotation would work with incremental compilation. I looked at the Gradle documentation for marking annotation processors as incremental and couldn't find `META-INF/gradle/incremental.annotation.processors` in the published jar for `classindex`.

> https://docs.gradle.org/4.10.3/userguide/java_plugin.html#sec:incremental_annotation_processing

Maybe I'm missing something? Or is this not supposed to work? Thanks

Gradle version: 4.10.3
JDK 8
classindex version: "org.atteo.classindex:classindex:3.4"

### PR DESCRIPTION
**Pull request by igor-makarov**
Supersedes #70
Fixes #61.

### CODE REVIEW

**Comment by igor-makarov** [comment]
@sentinelt please merge this as soon as you can. Thank you!

**Comment by igor-makarov** [comment]
@sentinelt Thank you!

Any idea when a release can be pushed out?

**Comment by sentinelt** [comment]
I've released version 3.12 with this change

**Comment by igor-makarov** [comment]
@sentinelt Thank you very much!

**Pull request merged**
